application: webappscl
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/(.*)
  static_files: statdata/images/\1
  upload: statdata/images/(.*)

- url: /js
  static_dir: statdata/js

- url: /.*
  script: scl.py
